using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

// This file is automatically generated by DataTableSettings.cs
// Do not modify this file

namespace TabbySheet
{
	public partial class FoodsTable : DataSheetBase<FoodsTable, FoodsTable.Data>
	{
		public enum UniqueKey
		{
			Id
		}

		private Dictionary<int, Data> idToData = new Dictionary<int, Data>();

		public FoodsTable() : base()
		{
			foreach(var data in datas)
				idToData.Add(data.Id, data);
		}

		[Serializable]
		public partial class Data : ISerializable
		{
			public int Id { get; set; }
			public string Name { get; set; }
			public int Price { get; set; }
			public bool CanBuy { get; set; }

			public Data() { }

			public Data(SerializationInfo info, StreamingContext context)
			{
				Id = (int)info.GetValue("Id", typeof(int));
				Name = (string)info.GetValue("Name", typeof(string));
				Price = (int)info.GetValue("Price", typeof(int));
				CanBuy = (bool)info.GetValue("CanBuy", typeof(bool));
			}

            public void GetObjectData(SerializationInfo info, StreamingContext context)
            {
				if (info == null)
					throw new ArgumentNullException("info");

				info.AddValue("Id", Id);
				info.AddValue("Name", Name);
				info.AddValue("Price", Price);
				info.AddValue("CanBuy", CanBuy);
            }
		}

		public Data GetDataById(int id)
		{
			return idToData[id];
		}
	}
}